name: Build Backend Infra

on: pull_request

jobs:
  savepr:
    if: github.event.pull_request.base.repo.full_name != github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v4
        name: Updload artifact
        with:
          name: pr
          path: pr/
